Web_1/Controllers/CategoriaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Datos;

namespace Web_1.Controllers
{
    public class CategoriaController : Controller
    {
        private DB_Trabajo_1Entities3 db = new DB_Trabajo_1Entities3();

        // GET: /Categoria__/
        public ActionResult Index()
        
        {
            ViewBag.LogHelper = LogHelper.Log.WriteFooter();
            return View(db.tTR_Categoria.ToList());
        }

        // GET: /Categoria/Details/5
        public ActionResult Details(int? id)
        {
            ViewBag.LogHelper = LogHelper.Log.WriteFooter();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tTR_Categoria ttr_categoria = db.tTR_Categoria.Find(id);
            if (ttr_categoria == null)
            {
                return HttpNotFound();
            }
            return View(ttr_categoria);
        }

        // GET: /Categoria/Create
        public ActionResult Create()
        {
            ViewBag.LogHelper = LogHelper.Log.WriteFooter();
            return View();
        }

        // POST: /Categoria/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="iIdCategoria,vNombreCategoria,iEstado")] tTR_Categoria ttr_categoria)
        {
            ViewBag.LogHelper = LogHelper.Log.WriteFooter();
            if (ModelState.IsValid)
            {
                db.tTR_Categoria.Add(ttr_categoria);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(ttr_categoria);
        }

        // GET: /Categoria/Edit/5
        public ActionResult Edit(int? id)
        {
            ViewBag.LogHelper = LogHelper.Log.WriteFooter();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tTR_Categoria ttr_categoria = db.tTR_Categoria.Find(id);
            if (ttr_categoria == null)
            {
                return HttpNotFound();
            }
            return View(ttr_categoria);
        }

        // POST: /Categoria/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="iIdCategoria,vNombreCategoria,iEstado")] tTR_Categoria ttr_categoria)
        {
            ViewBag.LogHelper = LogHelper.Log.WriteFooter();
            if (ModelState.IsValid)
            {
                db.Entry(ttr_categoria).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(ttr_categoria);
        }


        public int AfterDelete(int? id)
        {
            int iEliminar = 0;
            int Registros = db.tTR_Producto.Where(n => n.iIdCategoria == id).Count();


            if (Registros == 0)
            {
                iEliminar = 1;
            }

            return iEliminar;
        }


        // GET: /Categoria/Delete/5
        public ActionResult Delete(int? id)
        {
            ViewBag.LogHelper = LogHelper.Log.WriteFooter();
            int Idelete = 0;

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            tTR_Categoria ttr_categoria = db.tTR_Categoria.Find(id);
           
            if (ttr_categoria == null)
            {
                return HttpNotFound();
            }
            Idelete = AfterDelete(ttr_categoria.iIdCategoria);
            ttr_categoria.iEstadoEliminar = Idelete;
            return View(ttr_categoria);
        }

        // POST: /Categoria/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ViewBag.LogHelper = LogHelper.Log.WriteFooter();
            tTR_Categoria ttr_categoria = db.tTR_Categoria.Find(id);
            db.tTR_Categoria.Remove(ttr_categoria);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Web_1/Controllers/LoginController.cs
using Datos;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Web_1.Controllers
{
    public class LoginController : Controller
    {
        private DB_Trabajo_1Entities3 db = new DB_Trabajo_1Entities3();


        //
        // GET: /Login/
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ValidaLogeo()
        {
            //UsuarioController objUsuarioController = null;
            List<tTR_Usuarios> loenUsuario = null;
            tTR_Usuarios objUsuarios = null;
            try
            {
                loenUsuario = new List<tTR_Usuarios>();
               
                //IQueryable Personas;
                loenUsuario = db.tTR_Usuarios.Cast<tTR_Usuarios>().ToList();
                var sUser = Request.Form["txtUsuario"];
                var sPassword= Request.Form["txtPassword"];

                loenUsuario = loenUsuario.Where(x => x.vNombreUsuario == sUser && x.vPassword == sPassword && x.iEstado == 1).ToList();

                if (loenUsuario.Count == 1)
                {
                    foreach (var item in loenUsuario)
                    {
                        objUsuarios = new tTR_Usuarios();
                        objUsuarios.vNombre = item.vNombre;
                        objUsuarios.vApellidos = item.vApellidos;
                        objUsuarios.vNombreUsuario = item.vNombreUsuario;
                        objUsuarios.iIdRol = item.iIdRol;
                        objUsuarios.iEstado = item.iEstado;
                    }
                    Session["LogeoUsuario"] = objUsuarios;
                    Session["Nombres"] = objUsuarios.vNombre + " " + objUsuarios.vApellidos;
                    ViewBag.ValidaLogeo = "Validación correcta";
                    //Response.Redirect("/Home/Index");
                }
                else
                {
                   // Response.Redirect("/Login/Index");
                    ViewBag.ValidaLogeo = "El usuario y/o password son incorrectos, verifique con el administrador si el usuario se encuentra activo";
                }
                            

            }
            catch (Exception ex)
            {
                throw ex;
               
            }

            return Redirect("/Home/Index");
        }

        public ActionResult CerrarSession()
        {
            Session.Clear();
            Session.RemoveAll();
            return View("Index");
        }


        #region Codigo Que no Se Usa 
        //
        // GET: /Login/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Login/Create
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Login/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Login/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Login/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Login/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Login/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        #endregion
    }
}

Web_1/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Datos;

namespace Web_1.Controllers
{
    public class UsuarioController : Controller
    {
        private DB_Trabajo_1Entities3 db = new DB_Trabajo_1Entities3();

        // GET: /Usuario/
        public ActionResult Index()
        {
            ViewBag.LogHelper = LogHelper.Log.WriteFooter();
            var ttr_usuarios = db.tTR_Usuarios.Include(t => t.tTR_Roles);
            return View(ttr_usuarios.ToList());
        }

        // GET: /Usuario/Details/5
        public ActionResult Details(string id)
        {
            ViewBag.LogHelper = LogHelper.Log.WriteFooter();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tTR_Usuarios ttr_usuarios = db.tTR_Usuarios.Find(id);
            if (ttr_usuarios == null)
            {
                return HttpNotFound();
            }
            return View(ttr_usuarios);
        }

        // GET: /Usuario/Create
        public ActionResult Create()
        {
            ViewBag.LogHelper = LogHelper.Log.WriteFooter();
            ViewBag.iIdRol = new SelectList(db.tTR_Roles, "iIdUsuario", "vNombreRol");
            return View();
        }

        // POST: /Usuario/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "iIdUsuario,iIdRol,vNombreUsuario,vPassword,vNombre,vApellidos,iEstado")] tTR_Usuarios ttr_usuarios, HttpPostedFileBase files)
        {
            ViewBag.LogHelper = LogHelper.Log.WriteFooter();
            string urlLocal = "../..";
            if (ModelState.IsValid)
            {
                if (files == null && ttr_usuarios.sRutaImagen == null)
                {
                    ttr_usuarios.sRutaImagen = "../../WebImage/no_image.png";
                }
                else
                {
                    var fileName = string.Format("/WebImage/{0}",
                             files.FileName);
                    files.SaveAs(this.Server.MapPath(fileName));
                    ttr_usuarios.sRutaImagen = urlLocal + fileName;
                }
                db.tTR_Usuarios.Add(ttr_usuarios);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.iIdRol = new SelectList(db.tTR_Roles, "iIdUsuario", "vNombreRol", ttr_usuarios.iIdRol);
            return View(ttr_usuarios);
        }

        // GET: /Usuario/Edit/5
        public ActionResult Edit(string id)
        {
            ViewBag.LogHelper = LogHelper.Log.WriteFooter();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tTR_Usuarios ttr_usuarios = db.tTR_Usuarios.Find(id);
            if (ttr_usuarios == null)
            {
                return HttpNotFound();
            }
            ViewBag.iIdRol = new SelectList(db.tTR_Roles, "iIdUsuario", "vNombreRol", ttr_usuarios.iIdRol);
            return View(ttr_usuarios);
        }

        // POST: /Usuario/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "iIdUsuario,iIdRol,vNombreUsuario,vPassword,vNombre,vApellidos,iEstado")] tTR_Usuarios ttr_usuarios, HttpPostedFileBase files)
        {
            ViewBag.LogHelper = LogHelper.Log.WriteFooter();
            string urlLocal = "../..";
            if (ModelState.IsValid)
            {
                if (files == null && ttr_usuarios.sRutaImagen ==null)
                {
                    ttr_usuarios.sRutaImagen = "../../WebImage/no_image.png";
                }
                else
                {
                    var fileName = string.Format("/WebImage/{0}",
                             files.FileName);
                    files.SaveAs(this.Server.MapPath(fileName));
                    ttr_usuarios.sRutaImagen = urlLocal + fileName;
                }
                db.Entry(ttr_usuarios).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.iIdRol = new SelectList(db.tTR_Roles, "iIdUsuario", "vNombreRol", ttr_usuarios.iIdRol);
            return View(ttr_usuarios);
        }

        // GET: /Usuario/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tTR_Usuarios ttr_usuarios = db.tTR_Usuarios.Find(id);
            if (ttr_usuarios == null)
            {
                return HttpNotFound();
            }
            return View(ttr_usuarios);
        }

        // POST: /Usuario/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            ViewBag.LogHelper = LogHelper.Log.WriteFooter();
            tTR_Usuarios ttr_usuarios = db.tTR_Usuarios.Find(id);
            db.tTR_Usuarios.Remove(ttr_usuarios);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Web_1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Trabajo Final</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<script type="text/javascript">
    var VG_RUTA_SERVIDOR = "@Url.Content("~")";
</script>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Cibertec", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="nav-justified" style="text-align:right;">
                <ul class="nav navbar-nav">
                    @{
                        Datos.tTR_Usuarios objdatos = new Datos.tTR_Usuarios();
                        objdatos = (Datos.tTR_Usuarios)Session["LogeoUsuario"];
                        
                        if (objdatos != null)
                        {
                            ViewBag.sNombres = (string)Session["Nombres"];
                            if (objdatos.iIdRol == 1)
                            {
                                <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                                <li>@Html.ActionLink("Categorias", "Index", "Categoria")</li>
                                <li>@Html.ActionLink("Productos", "Index", "Productos")</li>
                                <li>@Html.ActionLink("Proveedores", "Index", "Proveedor")</li>
                                <li>@Html.ActionLink("Roles", "Index", "Roles")</li>
                                <li>@Html.ActionLink("Usuarios", "Index", "Usuario")</li>
                            }
                            else if (objdatos.iIdRol == 3)
                            {
                                <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                                <li>@Html.ActionLink("Categorias", "Index", "Categoria")</li>
                                <li>@Html.ActionLink("Productos", "Index", "Productos")</li>
                                <li>@Html.ActionLink("Proveedores", "Index", "Proveedor")</li>

                            }else
                            {
                                <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                            }
                        }else
                        {
                            Response.Redirect("/Login/Index");
                        }

                    }

                </ul>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="navbar-text">Hola,@ViewBag.sNombres </li> 
                    <li>  @Html.ActionLink("Cerrar Sesión", "CerrarSession", "Login", null, new { @class = "" }) </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>
    <!-- Modal -->
    <div class="modal fade" id="myModal2" role="dialog">
        <div class="modal-dialog modal-md css-modal-timer">
            <div class="modal-content css-modal-border-redondo">
                <div class="modal-header css-modal-header">
                    <div class="modal-title css-modal-title-text">
                        Trabajo Final Cibertec
                    </div>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="css-modal-timer-text text-justify">
                                <i class="pull-left fa fa-exclamation-circle fa-4x" style="color: #F56868"></i>
                                <span id="hddMessage">@TempData["Message"]</span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer css-modal-footer">
                    <button type="button" class="btn btn-xs btn-danger" data-dismiss="modal" id="modal-close">Cerrar</button>
                </div>
            </div>
        </div>
    </div>
    <!-- Modal Formularios -->
    <div class="modal fade" id="myModal" role="dialog">
        <div class="modal-dialog modal-md css-modal-timer">
            <div class="modal-content css-modal-border-redondo">
                <div class="modal-header css-modal-heasder">
                    <div class="modal-title css-modal-title-text">
                        Trabajo Final Cibertec
                    </div>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="css-modal-timer-text text-justify">
                                <i class="pull-left fa fa-exclamation-circle fa-4x" style="color: #F56868"></i>
                                <span id="hddMessage"></span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer css-modal-footer">
                    <button type="button" class="btn btn-xs btn-danger" data-dismiss="modal" id="modal-close">Cerrar</button>
                </div>
            </div>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
<footer>
    <p style="text-align:center;">&copy; @DateTime.Now.Year - @ViewBag.LogHelper </p>
</footer>
</html>